A few changes for error cases in combiner predeploy script

diff --git a/helm/charts/clinvar-combined-stream/pre-deploy-script b/helm/charts/clinvar-combined-stream/pre-deploy-script
--- a/helm/charts/clinvar-combined-stream/pre-deploy-script
+++ b/helm/charts/clinvar-combined-stream/pre-deploy-script
@@ -1,13 +1,22 @@
-#!/bin/sh
+#!/bin/zsh
 # print command trace
 set -x
 # exit on fail
 set -e
+# no unset parameters (only in calls)
+set -u
 
-input_topic=clinvar-raw-dev #-testdata_20210302
-output_topic=clinvar-combined-dev #-testdata_20210302
+#input_topic=clinvar-raw-testdata_20210302
+#output_topic=clinvar-combined-testdata_20210302
+input_topic=clinvar-raw-dev
+output_topic=clinvar-combined-dev
+
 cluster=clingen-streams-dev
 cluster_id=$(ccloud kafka cluster list | grep $cluster | awk '{print $1}')
+if [[ -z "$cluster_id" ]] ; then
+    echo "Cluster $cluster not found"
+    exit 1
+fi
 
 kafka_properties_file=./kafka-dev.properties
 if [[ ! -f "$kafka_properties_file" ]]; then
@@ -19,7 +28,7 @@ fi
 function topic_offset_to_zero {
     topic=$1
     group=$2
-    kafka-consumer-groups --command-config ./kafka-dev.properties \
+    kafka-consumer-groups --command-config "$kafka_properties_file" \
       --bootstrap-server pkc-4yyd6.us-east1.gcp.confluent.cloud:9092 \
       --reset-offsets \
       --to-offset 0 \
@@ -34,10 +43,8 @@ group=clinvar-combined-dev
 topic_offset_to_zero $input_topic $group
 
 echo "Deleting and recreating output topic"
-# leave +e untoggled so topic deletes are allowed to fail
-set +e
-ccloud kafka topic delete --cluster $cluster_id $output_topic
-set -e
+# topic deletes are allowed to fail
+ccloud kafka topic delete --cluster $cluster_id $output_topic || true
 
 # switch -e so exits on failure
 ccloud kafka topic create --cluster $cluster_id $output_topic \
